create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  created_by bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null default 'Member' check (role in ('Admin', 'Member')),
  joined_at timestamptz not null default now(),
  unique(project_id, user_id)
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  title text not null,
  description text default '',
  priority text not null default 'MEDIUM' check (priority in ('LOW', 'MEDIUM', 'HIGH')),
  status text not null default 'TODO' check (status in ('TODO', 'IN_PROGRESS', 'DONE')),
  due_date date,
  assigned_to bigint references public.users(id) on delete set null,
  created_by bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_project_members_user_id on public.project_members(user_id);
create index if not exists idx_project_members_project_id on public.project_members(project_id);
create index if not exists idx_tasks_project_id on public.tasks(project_id);
create index if not exists idx_tasks_assigned_to on public.tasks(assigned_to);

alter table public.users disable row level security;
alter table public.projects disable row level security;
alter table public.project_members disable row level security;
alter table public.tasks disable row level security;
